package: generator-nbextension

platform:
  - linux-64
  - osx-64
  - win-64
  - linux-32
  - win-32

install:
  - conda config --add channels anaconda-nb-extensions
  - conda config --add channels javascript
  - conda install nodejs
  - npm dedupe
  - conda install yoeman


script:
  - conda build --quiet conda.recipe

after_script:
  - npm install
  - npm link
  - yo nbextension:app --help

build_targets: conda
