package: generator-nbextension
user: anaconda-notebook

platform:
  - linux-64
  - osx-64

script:
  - conda build conda.recipe -c anaconda-notebook -c javascript

install:
  - conda install yoeman -c javascript

test:
  - npm install
  - npm link
  - yo nbextension:app --help

build_targets: conda
