package:
  name: <%= parameterized %>
  version: 0.1.0

requirements:
  build:
    - python
  run:
    - nbsetuptools
    - nb_config_manager

source:
  path: ../

about:
  home: TBD
  license: <%= license %>
