package:
  name: generator-nbextension
  version: 0.1.4

requirements:
  build:
    - gulp
    - nodejs
    - yoeman
  run:
    - nodejs
    - nbsetuptools
    - yoeman

about:
  home: http://github.com/anaconda-nb-extensions/generator-nbextension
  license: BSD
