package:
  name: generator-nbextension
  version: 0.1.2

requirements:
  build:
    - gulp
    - nodejs
    - yoeman
  run:
    - nodejs
    - nbsetuptools
    - yoeman

about:
  home: http://github.com/anaconda-notebook/generator-nbextension
  license: TBD

